# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "reform" ]
# shield: [ "corne_left", "corne_right" ]
include:
  - board: reform
    snippet: rp2-boot-mode-retention studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: reform_standalone
  - board: reform
    snippet: rp2-boot-mode-retention studio-rpc-usb-uart reform-classic
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: reform_classic
  - board: reform
    snippet: rp2-boot-mode-retention studio-rpc-usb-uart reform-next
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: reform_next
  - board: pocket_reform
    snippet: rp2-boot-mode-retention studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: pocket_reform
